### ISSUE TITLE
Create a higher level api to cut down on test boilerplate

### ISSUE THREAD

**Issue by wadells** [wadells/gravitational-audition#6]
Per https://github.com/javins/gravitational-audition/pull/5#discussion_r335762006 and https://github.com/javins/gravitational-audition/pull/5#discussion_r335762409, we could abstract the tests a bit more by having a slightly higher level API (e.g. `create()`, `delete()` in addition to `get()` and `post()` to interact with.

**Comment by klizhentas** [comment]
@javins I would not implement this comment at this point for the MVP.

**Comment by wadells** [comment]
Out of scope.
